"""
Analysis Domain Models for TradeScout

Models representing trading analysis, strategies, and suggestions.
These models are used by the AnalysisInterface operations.
"""

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Dict, List, Optional

from .models_asset import Asset, MarketQuote
from .models_base import MarketStatus


class TradeSide(Enum):
    """Trade direction"""
    LONG = "long"
    SHORT = "short"


class TradeStatus(Enum):
    """Trade execution status"""
    SUGGESTED = "suggested"
    PENDING = "pending"
    EXECUTED = "executed"
    CLOSED = "closed"
    CANCELLED = "cancelled"
    EXPIRED = "expired"


class RiskLevel(Enum):
    """Risk levels for trades"""
    CONSERVATIVE = "conservative"
    MODERATE = "moderate"
    AGGRESSIVE = "aggressive"


class ConfidenceLevel(Enum):
    """Confidence levels for trade suggestions"""
    LOW = "low"  # 50-70%
    MEDIUM = "medium"  # 70-85%
    HIGH = "high"  # 85-95%
    VERY_HIGH = "very_high"  # 95%+


class GapType(Enum):
    """Gap classification based on characteristics"""
    COMMON = "common"  # <2% size, likely to fill
    BREAKAWAY = "breakaway"  # 2-5% size, trend initiation
    CONTINUATION = "continuation"  # 2-7% size, trend acceleration
    EXHAUSTION = "exhaustion"  # >5% size, trend termination
    OPENING_DRIVE = "opening_drive"  # Strong directional gap


@dataclass
class GapAnalysis:
    """Gap analysis for extended hours trading"""
    
    asset: Asset
    analysis_time: datetime
    session_type: MarketStatus  # PRE_MARKET or AFTER_HOURS
    
    # Gap metrics
    previous_close: Decimal
    current_price: Decimal
    gap_size: Decimal  # Absolute dollar amount
    gap_percent: Decimal  # Percentage
    
    # Gap characteristics
    gap_type: GapType
    gap_direction: str  # "up" or "down"
    
    # Volume analysis
    volume: int
    relative_volume: Decimal  # vs average
    volume_quality: str  # "thin", "normal", "heavy"
    
    # Supporting factors
    catalyst: Optional[str] = None  # News, earnings, etc.
    catalyst_strength: Optional[str] = None  # "weak", "moderate", "strong"
    
    # Historical context
    similar_gaps_filled: Optional[Decimal] = None  # Historical fill rate
    average_fill_time: Optional[int] = None  # Minutes to fill
    
    # Probability assessment
    fill_probability: Decimal = Decimal("0.5")  # 0.0 to 1.0
    continuation_probability: Decimal = Decimal("0.5")  # 0.0 to 1.0
    
    @property
    def is_tradeable(self) -> bool:
        """Check if gap is suitable for trading"""
        return (
            abs(self.gap_percent) >= 2.0 and
            abs(self.gap_percent) <= 10.0 and
            self.volume_quality != "thin"
        )
    
    @property
    def suggested_strategy(self) -> str:
        """Suggest trading strategy based on gap type"""
        if self.gap_type == GapType.EXHAUSTION:
            return "fade"  # Trade against the gap
        elif self.gap_type == GapType.BREAKAWAY:
            return "follow"  # Trade with the gap
        elif self.gap_type == GapType.COMMON:
            return "fade_partial"  # Expect partial fill
        else:
            return "monitor"  # Wait for confirmation


@dataclass
class TradeSuggestion:
    """Trade suggestion generated by analysis"""
    
    # Required fields first
    asset: Asset
    side: TradeSide
    analysis_type: str  # "gap", "momentum", "reversal", etc.
    confidence: ConfidenceLevel
    confidence_score: Decimal  # 0.0 to 1.0
    risk_level: RiskLevel
    suggested_entry: Decimal
    stop_loss: Decimal
    take_profit_1: Decimal
    position_size_percent: Decimal  # % of portfolio
    valid_until: datetime
    risk_amount: Decimal  # Dollar risk per share
    reward_amount: Decimal  # Expected profit per share
    risk_reward_ratio: Decimal
    rationale: str
    
    # Optional fields with defaults last
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = field(default_factory=datetime.now)
    take_profit_2: Optional[Decimal] = None
    max_position_value: Optional[Decimal] = None
    max_hold_time_hours: Optional[int] = None
    supporting_factors: List[str] = field(default_factory=list)
    risk_factors: List[str] = field(default_factory=list)
    
    # Related analysis
    gap_analysis: Optional[GapAnalysis] = None
    technical_signals: List[str] = field(default_factory=list)
    
    @property
    def is_valid(self) -> bool:
        """Check if suggestion is still valid"""
        return datetime.now() < self.valid_until
    
    @property
    def expected_return(self) -> Decimal:
        """Calculate expected return percentage"""
        if self.suggested_entry > 0:
            return ((self.take_profit_1 - self.suggested_entry) / self.suggested_entry) * 100
        return Decimal("0")


@dataclass
class ExtendedHoursActivity:
    """Extended hours market activity analysis"""
    
    # Required fields first
    timestamp: datetime
    session_type: MarketStatus  # PRE_MARKET or AFTER_HOURS
    high_volume_stocks: List[MarketQuote]
    gap_ups: List[GapAnalysis]
    gap_downs: List[GapAnalysis]
    biggest_gaps: List[GapAnalysis]
    highest_volume: List[MarketQuote]
    
    # Optional fields with defaults
    futures_indication: Optional[Dict[str, Decimal]] = None  # ES, NQ, etc.
    overseas_markets: Optional[Dict[str, Decimal]] = None
    
    @property
    def market_direction(self) -> str:
        """Assess overall market direction"""
        if len(self.gap_ups) > len(self.gap_downs) * 1.5:
            return "bullish"
        elif len(self.gap_downs) > len(self.gap_ups) * 1.5:
            return "bearish"
        else:
            return "mixed"


@dataclass
class TechnicalSignal:
    """Technical analysis signal"""
    
    asset: Asset
    timestamp: datetime
    timeframe: str  # "1m", "5m", "1h", "1d"
    
    # Signal details
    signal_type: str  # "breakout", "reversal", "continuation"
    signal_name: str  # "golden_cross", "rsi_oversold", etc.
    strength: str  # "weak", "moderate", "strong"
    
    # Key levels
    trigger_price: Decimal
    support_level: Optional[Decimal] = None
    resistance_level: Optional[Decimal] = None
    
    # Indicators
    indicator_values: Dict[str, Decimal] = field(default_factory=dict)
    
    @property
    def is_actionable(self) -> bool:
        """Check if signal is strong enough to act on"""
        return self.strength in ["moderate", "strong"]


@dataclass
class PerformanceMetrics:
    """Performance tracking for strategies and trades"""
    
    strategy_name: str
    period_start: datetime
    period_end: datetime
    
    # Trade statistics
    total_trades: int
    winning_trades: int
    losing_trades: int
    
    # Returns
    total_return: Decimal
    average_return: Decimal
    best_trade: Decimal
    worst_trade: Decimal
    
    # Risk metrics
    sharpe_ratio: Optional[Decimal] = None
    max_drawdown: Optional[Decimal] = None
    win_rate: Optional[Decimal] = None
    
    # Timing
    average_hold_time_hours: Optional[float] = None
    
    @property
    def profit_factor(self) -> Optional[Decimal]:
        """Calculate profit factor"""
        if self.losing_trades > 0 and hasattr(self, 'gross_profit') and hasattr(self, 'gross_loss'):
            return abs(self.gross_profit / self.gross_loss)
        return None